<a href="https://colab.research.google.com/github/jjainga/Tensorflow_course/blob/main/tensorflow_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
%tensorflow_version 2.x # this line is to make sure we are using the lastest version of tensorflow

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [10]:
#creating tensors
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(69, tf.int16)
floating = tf.Variable(69.69, tf.float64)

print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=69>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=69.69>


In [19]:
#rank of a tensor
rank_tensor = tf.Variable(["test"], tf.string)
#you need to have a uniform amount of numbers in the matrix
rank2_tensor = tf.Variable([["test", "one"], ["test","two"]], tf.string)

#tf.rank(rank_tensor)
tf.rank(rank2_tensor)




<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [22]:
#the shape below says we have 2 lists and each list has 2 elements
rank2_tensor.shape

TensorShape([2, 2])

In [25]:
#reshaping tensor shapes
#one outer list with 2 lists inside it and 3 elements in each list
tensor1 = tf.ones([1,2,3])
#two outer lists with 3 lists in each with 1 element in each of those inner list
tensor2 = tf.reshape(tensor1, [2,3,1])
#3 outer list and the -1 distributes the elements uniformily to the list created
tensor3 = tf.reshape(tensor1, [3,-1])

#reshape must match the original number of elements in the original tensor


In [24]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
#types of tensors
#Variables
#Constant
#Placeholder
#SparseTensor

#all but Variable tensors can not change in value, if using a Variable tensor we use this when we think the tnsor is going to change over time


#elvauating tensors

In [28]:
t = tf.ones([5,5,5,5])
#print(t)

t_2 = tf.reshape(t, [625])
#or
t_3 = tf.reshape(t, [125,5])
print(t_2)

tf.Tensor(
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 